#!/usr/bin/env bash
_serverlist() 
{
	if [ "${#COMP_WORDS[@]}" != "2" ]; then
    		return
	fi

	local suggestions=($(compgen -W "$(echo $(cat ~/.ssh_servers | cut -d ":" -f1))" -- "${COMP_WORDS[1]}"))

	if [ "${#suggestions[@]}" == "1" ]; then
    		# if there's only one match, we remove the command literal
		# to proceed with the automatic completion of the number
		local number=$(echo ${suggestions[0]/%\ */})
		COMPREPLY=("$number")
	else
		# more than one suggestions resolved,
		# respond with the suggestions intact
		COMPREPLY=("${suggestions[@]}")
	fi
}

complete -F _serverlist sshs
